## Documentation: http://docs.travis-ci.org/user/languages/julia/
language: julia
codecov: true
os:
  - linux
  - osx
julia:
  - 1.2
  - 1.3
  - nightly

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)


notifications:
  email: false

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

jobs:
  allow_failures:
    - julia: nightly
    - os: osx
  fast_finish: true
    - stage: "Documentation"
      os: linux
      julia: 1.2
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
