## Documentation: http://docs.travis-ci.org/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - nightly
notifications:
  email: false

## uncomment the following lines to allow failures on nightly julia
## (tests will run but not make your overall status red)
matrix:
  allow_failures:
  - julia: nightly
  - os: osx

## uncomment and modify the following lines to manually install system packages
#addons:
#  apt: # apt-get for linux
#    packages:
#    - gfortran
#before_script: # homebrew for mac
#  - if [ $TRAVIS_OS_NAME = osx ]; then brew install gcc; fi

## uncomment the following lines to override the default test script
script:
  - julia --color=yes -e "if VERSION < v\"0.7.0-DEV.5183\"; using Pkg; Pkg.develop(pwd()); 
  - cd PowerSystems
  - julia --project; import Pkg; Pkg.build();"
  - julia --check-bounds=yes --color=yes -e "if VERSION < v\"0.7.0\"; Pkg.test(\"PowerSystems\", coverage=true); else import Pkg; Pkg.test(coverage=true); end"

after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
